<?php

/**
 * @file
 * Contains lib_unb_custom_entity.module.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function lib_unb_custom_entity_theme() {
  return [
    'entity_table' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Implements template_preprocess_hook.
 *
 * @param array $variables
 *   An array of variables to pass to the template.
 */
function template_preprocess_entity_table(&$variables) {
  $variables['table'] = [
    '#type' => 'table',
    '#header' => [
      'label' => t('Label'),
      'value' => t('Value'),
    ],
    '#empty' => t('Nothing to display.'),
    '#rows' => [],
  ];

  foreach (Element::children($variables['element']) as $key) {
    $field = $variables['element'][$key];
    $variables['table']['#rows'][] = [
      'label' => $field['#title'],
      'value' => ['data' => $field],
    ];
  }
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function lib_unb_custom_entity_field_formatter_info_alter(array &$info) {
  if (isset($info['entity_reference_label'])) {
    $info['entity_reference_label']['field_types'][] = 'creator';
    $info['entity_reference_label']['field_types'][] = 'editor';
  }
}
