<?php

/**
 * @file
 * Contains lib_unb_custom_entity.module.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function lib_unb_custom_entity_theme() {
  return [
    'entity_table' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Implements template_preprocess_hook.
 *
 * @param array $variables
 *   An array of variables to pass to the template.
 */
function template_preprocess_entity_table(&$variables) {
  $table = [
    '#type' => 'table',
    '#header' => [
      'label' => t('Label'),
      'value' => t('Value'),
    ],
    '#empty' => t('Nothing to display.'),
    '#rows' => [],
  ];

  foreach (Element::children($variables['element']) as $field_id) {
    $field = $variables['element'][$field_id];
    if (isset($field['#title'])) {
      $index = $field['#row']['#weight'];
      $table['#rows'][$index] = $field['#row'];
    }
  }

  ksort($table['#rows']);
  $variables['table'] = $table;
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function lib_unb_custom_entity_field_formatter_info_alter(array &$info) {
  if (isset($info['entity_reference_label'])) {
    $info['entity_reference_label']['field_types'][] = 'creator';
    $info['entity_reference_label']['field_types'][] = 'editor';
  }
}
